/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.parabitinss;

/**
 *
 * @author arvin
 */
public class PbtRegCheck extends javax.swing.JDialog {
    public QrScanner qrScr;
    
    public PbtRegCheck(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Hide advanced options until a check type is selected
        rb1.setVisible(false);
        rb2.setVisible(false);
        tf1.setVisible(false);
        b1.setVisible(false);
        lb1.setVisible(false);

        setTitle("INSS — Registration Check");
        setLocationRelativeTo(null);

        // ── Add a "Scan QR" button below the existing layout ──────
        // The QR scanner fills tf1 automatically when it decodes a code.
        javax.swing.JButton qrBtn = new javax.swing.JButton("📷  Scan QR Code");
        qrBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        qrBtn.setBackground(new java.awt.Color(46, 116, 181));
        qrBtn.setForeground(java.awt.Color.WHITE);
        qrBtn.setFocusPainted(false);
        qrBtn.addActionListener(e -> launchQrScanner());

        // Add to bottom of dialog content pane
        getContentPane().add(qrBtn,
            new java.awt.BorderLayout() {{}} );  // NOTE: if GroupLayout, add manually:
        // Find "pack();" at end of initComponents and add before it:
        //    getContentPane().add(qrBtn);
        // OR place it using the layout below which works regardless of layout manager:
        javax.swing.SwingUtilities.invokeLater(() -> {
            getContentPane().add(qrBtn);
            pack();
            setLocationRelativeTo(null);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chkb1 = new javax.swing.JCheckBox();
        chkb2 = new javax.swing.JCheckBox();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        tf1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registration Check For");

        chkb1.setText("Vehicle");
        chkb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkb1ActionPerformed(evt);
            }
        });

        chkb2.setText("Person");
        chkb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkb2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb1);
        rb1.setText("Personal Vehicle");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("Commercial Vehicle");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        b1.setText("Submit");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        lb1.setText("Enter Vehicle number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkb1)
                .addGap(86, 86, 86)
                .addComponent(chkb2)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb2)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(108, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkb1)
                    .addComponent(chkb2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1))
                .addGap(26, 26, 26)
                .addComponent(b1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkb1ActionPerformed
        if(chkb1.isSelected() && chkb1.getText().equals("Vehicle")){
            rb1.setVisible(true);
            rb2.setVisible(true);
            lb1.setText("Enter Vehicle Nnumber");
        }
    }//GEN-LAST:event_chkb1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        //GEN-FIRST:event_b1ActionPerformed

        UserSession.getInstance().resetInactivityTimer();

        String input = tf1.getText().trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter a value or scan a QR code.",
                "Input Required", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (chkb1.isSelected()) {
            // ── VEHICLE CHECK ──────────────────────────────────────
            // Strip INSS QR payload if user scanned a QR
            // QR format: INSS|VEH|{VRegNo}|{OwnerName}|{SerialNo}
            String vehicleNo = input;
            if (input.startsWith("INSS|VEH|")) {
                String[] parts = input.split("\\|");
                vehicleNo = parts.length > 2 ? parts[2] : input;
            }

            // Open PbtVhReg in check mode — vhCheck() loads all details
            PbtVhReg dialog = new PbtVhReg(new javax.swing.JFrame(), true, vehicleNo);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

            // Log this check attempt
            logCheckAttempt(vehicleNo, "VEHICLE", "CHECKED");

        } else if (chkb2.isSelected()) {
            // ── PERSON CHECK ───────────────────────────────────────
            // Strip INSS QR payload if scanned
            // QR format: INSS|PERSON|{GroupCode}|{LeaderName}|{Count}
            String identifier = input;
            if (input.startsWith("INSS|PERSON|")) {
                String[] parts = input.split("\\|");
                identifier = parts.length > 2 ? parts[2] : input; // GroupCode
            }

            lookupPerson(identifier);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select 'Vehicle' or 'Person' before submitting.",
                "Select Check Type", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
        //GEN-LAST:event_b1ActionPerformed
    }//GEN-LAST:event_b1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        tf1.setVisible(true);
        lb1.setVisible(true);
        b1.setVisible(true);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        tf1.setVisible(true);
        lb1.setVisible(true);
        b1.setVisible(true);
    }//GEN-LAST:event_rb2ActionPerformed

    private void chkb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkb2ActionPerformed
         // Uncheck vehicle option (mutual exclusion)
        chkb1.setSelected(false);
        rb1.setVisible(false);
        rb2.setVisible(false);

        lb1.setText("Enter Aadhaar No / Group Code");
        lb1.setVisible(true);
        tf1.setVisible(true);
        b1.setVisible(true);
        tf1.requestFocus();
    }//GEN-LAST:event_chkb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PbtRegCheck dialog = new PbtRegCheck(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Opens the QR scanner with a callback.
     * When a code is scanned, fills tf1 and automatically triggers b1.
     */
    private void launchQrScanner() {
        UserSession.getInstance().resetInactivityTimer();
        // QrScanner callback constructor — defined in Sprint 1
        new QrScanner(decodedText -> {
            tf1.setText(decodedText);
            // Auto-trigger lookup after half-second (lets UI update first)
            javax.swing.Timer delay = new javax.swing.Timer(500, e -> b1ActionPerformed(null));
            delay.setRepeats(false);
            delay.start();
        });
    }

    /**
     * Looks up a person in personreg by Aadhaar number OR GroupCode.
     * Shows a summary dialog with person/group details.
     */
    private void lookupPerson(String identifier) {
        try {
            ParabitDBC db = new ParabitDBC();

            // Try Aadhaar lookup first (12 digits), then GroupCode
            boolean isAadhaar = identifier.replaceAll("\\D", "").length() == 12;

            String sql;
            if (isAadhaar) {
                sql = "SELECT PersonName, MobileNo, AadharNo, Gender, Age, " +
                      "TownCity, State, GroupCode, IsGroupLeader, RegDate " +
                      "FROM personreg WHERE AadharNo = ?";
            } else {
                // Group code — show all members of the group
                sql = "SELECT PersonName, MobileNo, AadharNo, Gender, Age, " +
                      "TownCity, State, GroupCode, IsGroupLeader, RegDate " +
                      "FROM personreg WHERE GroupCode = ? ORDER BY IsGroupLeader DESC";
            }

            db.ps = db.con.prepareStatement(sql);
            db.ps.setString(1, identifier);
            db.rs = db.ps.executeQuery();

            if (!db.rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No registration found for: " + identifier + "\n\n"
                    + "This person/group is NOT registered for the event.",
                    "Not Found ❌",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                logCheckAttempt(identifier, "PERSON", "NOT_FOUND");
                return;
            }

            // Build result display
            StringBuilder sb = new StringBuilder();
            sb.append("✅  REGISTERED\n");
            sb.append("─────────────────────────────\n");
            int count = 0;
            do {
                count++;
                boolean isLeader = db.rs.getInt("IsGroupLeader") == 1;
                sb.append(isLeader ? "👤 LEADER  " : "👥 Member  ");
                sb.append(db.rs.getString("PersonName")).append("\n");
                sb.append("   Aadhaar : ").append(db.rs.getString("AadharNo")).append("\n");
                sb.append("   Mobile  : ").append(db.rs.getString("MobileNo")).append("\n");
                sb.append("   Gender  : ").append(db.rs.getString("Gender"))
                  .append("  |  Age: ").append(db.rs.getString("Age")).append("\n");
                sb.append("   Location: ").append(db.rs.getString("TownCity"))
                  .append(", ").append(db.rs.getString("State")).append("\n");
                sb.append("   Group   : ").append(db.rs.getString("GroupCode")).append("\n");
                sb.append("   Reg Date: ").append(db.rs.getString("RegDate")).append("\n");
                if (count < 10) sb.append("\n"); // separator between members
            } while (db.rs.next() && count < 10); // cap at 10 rows in dialog

            if (count == 10) sb.append("... and more members in this group.\n");

            javax.swing.JOptionPane.showMessageDialog(this,
                sb.toString(), "Person Found ✅",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            logCheckAttempt(identifier, "PERSON", "FOUND");

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Database error during lookup: " + ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Logs every check attempt to personlog table for audit trail.
     * Silently does nothing if the log table doesn't exist yet.
     */
    private void logCheckAttempt(String identifier, String checkType, String result) {
        try {
            ParabitDBC db = new ParabitDBC();
            db.ps = db.con.prepareStatement(
                "INSERT INTO personlog(Identifier, CheckType, CheckResult, " +
                "CheckedBy, CheckTime) VALUES(?, ?, ?, ?, NOW())");
            db.ps.setString(1, identifier);
            db.ps.setString(2, checkType);
            db.ps.setString(3, result);
            db.ps.setString(4, UserSession.getInstance().getEmpId());
            db.ps.executeUpdate();
        } catch (Exception ex) {
            // Log table may not exist yet — non-critical, don't crash
            System.err.println("[PbtRegCheck] logCheckAttempt skipped: " + ex.getMessage());
        }
    }

    /**
     * Public method called by QrScanner via callback.
     * Sets tf1 text and fires the lookup automatically.
     * Can also be called directly: regCheckInstance.receiveQrResult("INSS|VEH|...");
     */
    public void receiveQrResult(String decodedText) {
        tf1.setText(decodedText);
        b1ActionPerformed(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkb1;
    private javax.swing.JCheckBox chkb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    protected javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
